apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    env: prod
spec:
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  type: ClusterIP
  selector:
    app: postgres