apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp
  labels:
    env: prod
    app: ic-webapp
spec:
  selector:
    matchLabels:
      app: ic-webapp
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      containers:
        - name: ic-webapp
          image: akakanu/ic-webapp:v1.0
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ODOO_URL
              value: http://172.17.0.1:30069/
            - name: PGADMIN_URL
              value: http://172.17.0.1:30050/